# Generated by Django 4.1.3 on 2022-12-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_date',
        ),
    ]
